[log]
level = "info"
format = "text"
add_source = false

[server]
addr = ":8080"
public_url = "https://discord.cmpf-tools.de/"

[database]
host = "localhost" # use "db" with compose.yml
port = 5432
username = "ca-global-bot"
password = "password"
database = "ca-global-bot"
ssl_mode = "disable"

[bot]
token = ""
guild_id = 0
log_channel_id = 0

[oauth]
client_id = 0
client_secret = ""

[recheck]
# how often members are rechecked
interval = "24h"
reauth_grace = "72h"

# CA source guild id -> region role id on United
[whitelist]
# "111111111111111111" = "222222222222222222"
