// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type OauthToken struct {
	UserID         int64
	AccessToken    string
	RefreshToken   string
	ExpiresAt      pgtype.Timestamptz
	SourceGuildIds []int64
	ReauthDeadline pgtype.Timestamptz
	LastCheckedAt  pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}
