// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth_tokens.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearReauthDeadline = `-- name: ClearReauthDeadline :exec
UPDATE oauth_tokens
SET reauth_deadline = NULL,
    updated_at      = now()
WHERE user_id = $1
`

func (q *Queries) ClearReauthDeadline(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, clearReauthDeadline, userID)
	return err
}

const deleteOAuthToken = `-- name: DeleteOAuthToken :exec
DELETE
FROM oauth_tokens
WHERE user_id = $1
`

func (q *Queries) DeleteOAuthToken(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteOAuthToken, userID)
	return err
}

const getOAuthToken = `-- name: GetOAuthToken :one
SELECT user_id, access_token, refresh_token, expires_at, source_guild_ids, reauth_deadline, last_checked_at, updated_at
FROM oauth_tokens
WHERE user_id = $1
`

func (q *Queries) GetOAuthToken(ctx context.Context, userID int64) (OauthToken, error) {
	row := q.db.QueryRow(ctx, getOAuthToken, userID)
	var i OauthToken
	err := row.Scan(
		&i.UserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.SourceGuildIds,
		&i.ReauthDeadline,
		&i.LastCheckedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExpiredReauth = `-- name: ListExpiredReauth :many
SELECT user_id, access_token, refresh_token, expires_at, source_guild_ids, reauth_deadline, last_checked_at, updated_at
FROM oauth_tokens
WHERE reauth_deadline IS NOT NULL
  AND reauth_deadline <= $1
ORDER BY user_id
`

func (q *Queries) ListExpiredReauth(ctx context.Context, reauthDeadline pgtype.Timestamptz) ([]OauthToken, error) {
	rows, err := q.db.Query(ctx, listExpiredReauth, reauthDeadline)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OauthToken
	for rows.Next() {
		var i OauthToken
		if err := rows.Scan(
			&i.UserID,
			&i.AccessToken,
			&i.RefreshToken,
			&i.ExpiresAt,
			&i.SourceGuildIds,
			&i.ReauthDeadline,
			&i.LastCheckedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOAuthTokens = `-- name: ListOAuthTokens :many
SELECT user_id, access_token, refresh_token, expires_at, source_guild_ids, reauth_deadline, last_checked_at, updated_at
FROM oauth_tokens
ORDER BY user_id
`

func (q *Queries) ListOAuthTokens(ctx context.Context) ([]OauthToken, error) {
	rows, err := q.db.Query(ctx, listOAuthTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OauthToken
	for rows.Next() {
		var i OauthToken
		if err := rows.Scan(
			&i.UserID,
			&i.AccessToken,
			&i.RefreshToken,
			&i.ExpiresAt,
			&i.SourceGuildIds,
			&i.ReauthDeadline,
			&i.LastCheckedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setReauthDeadline = `-- name: SetReauthDeadline :one
UPDATE oauth_tokens
SET reauth_deadline = $2,
    updated_at      = now()
WHERE user_id = $1
RETURNING user_id, access_token, refresh_token, expires_at, source_guild_ids, reauth_deadline, last_checked_at, updated_at
`

type SetReauthDeadlineParams struct {
	UserID         int64
	ReauthDeadline pgtype.Timestamptz
}

func (q *Queries) SetReauthDeadline(ctx context.Context, arg SetReauthDeadlineParams) (OauthToken, error) {
	row := q.db.QueryRow(ctx, setReauthDeadline, arg.UserID, arg.ReauthDeadline)
	var i OauthToken
	err := row.Scan(
		&i.UserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.SourceGuildIds,
		&i.ReauthDeadline,
		&i.LastCheckedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLastChecked = `-- name: UpdateLastChecked :exec
UPDATE oauth_tokens
SET last_checked_at = now(),
    updated_at      = now()
WHERE user_id = $1
`

func (q *Queries) UpdateLastChecked(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, updateLastChecked, userID)
	return err
}

const updateTokensAndSources = `-- name: UpdateTokensAndSources :one
UPDATE oauth_tokens
SET access_token     = $2,
    refresh_token    = $3,
    expires_at       = $4,
    source_guild_ids = $5,
    reauth_deadline  = NULL,
    last_checked_at  = now(),
    updated_at       = now()
WHERE user_id = $1
RETURNING user_id, access_token, refresh_token, expires_at, source_guild_ids, reauth_deadline, last_checked_at, updated_at
`

type UpdateTokensAndSourcesParams struct {
	UserID         int64
	AccessToken    string
	RefreshToken   string
	ExpiresAt      pgtype.Timestamptz
	SourceGuildIds []int64
}

func (q *Queries) UpdateTokensAndSources(ctx context.Context, arg UpdateTokensAndSourcesParams) (OauthToken, error) {
	row := q.db.QueryRow(ctx, updateTokensAndSources,
		arg.UserID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.ExpiresAt,
		arg.SourceGuildIds,
	)
	var i OauthToken
	err := row.Scan(
		&i.UserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.SourceGuildIds,
		&i.ReauthDeadline,
		&i.LastCheckedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertOAuthToken = `-- name: UpsertOAuthToken :one
INSERT INTO oauth_tokens (user_id, access_token, refresh_token, expires_at, source_guild_ids, reauth_deadline,
                          last_checked_at, updated_at)
VALUES ($1, $2, $3, $4, $5, NULL, now(), now())
ON CONFLICT (user_id) DO UPDATE
    SET access_token     = EXCLUDED.access_token,
        refresh_token    = EXCLUDED.refresh_token,
        expires_at       = EXCLUDED.expires_at,
        source_guild_ids = EXCLUDED.source_guild_ids,
        reauth_deadline  = NULL,
        last_checked_at  = now(),
        updated_at       = now()
RETURNING user_id, access_token, refresh_token, expires_at, source_guild_ids, reauth_deadline, last_checked_at, updated_at
`

type UpsertOAuthTokenParams struct {
	UserID         int64
	AccessToken    string
	RefreshToken   string
	ExpiresAt      pgtype.Timestamptz
	SourceGuildIds []int64
}

func (q *Queries) UpsertOAuthToken(ctx context.Context, arg UpsertOAuthTokenParams) (OauthToken, error) {
	row := q.db.QueryRow(ctx, upsertOAuthToken,
		arg.UserID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.ExpiresAt,
		arg.SourceGuildIds,
	)
	var i OauthToken
	err := row.Scan(
		&i.UserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.SourceGuildIds,
		&i.ReauthDeadline,
		&i.LastCheckedAt,
		&i.UpdatedAt,
	)
	return i, err
}
